tabWidth: 4
trailingComma: none
arrowParens: avoid
plugins:
    - prettier-plugin-astro
    - prettier-plugin-tailwindcss
    - "@ianvs/prettier-plugin-sort-imports"
overrides:
    - files: "package.json"
      options:
          tabWidth: 2
